AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata:

Parameters:
  EC2InstanceType:
    Type: String
  EC2AMI:
    # This is a special parameter type that allows our template to get the latest AMI without having to specify the exact version
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
Mappings:

Conditions:

Resources:

Outputs:
